# Generated by Django 5.1.4 on 2025-03-10 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_package_order_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='inventory',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
