# Generated by Django 5.1.4 on 2025-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_packages_order_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
