# Generated by Django 5.1.4 on 2025-03-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_packageitem_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='payed',
        ),
    ]
