# Generated by Django 5.1.4 on 2025-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_total_price_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'package'), name='cart_package_uniqueness'),
        ),
    ]
