# Generated by Django 5.1.4 on 2025-03-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_code_alter_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'package'), name='order_package_uniqueness')],
            },
        ),
    ]
