# Generated by Django 5.1.4 on 2025-03-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_packageitem_package_product_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='store.order'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='ORD-24310325-2492BA', max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
