# Generated by Django 5.1.4 on 2025-03-31 22:13

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_order_email_remove_order_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default=store.models.generate_order_code, max_length=19, unique=True),
        ),
    ]
