# Generated by Django 5.1.4 on 2025-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
