# Generated by Django 5.1.4 on 2025-04-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_total_price_alter_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
