# Generated by Django 5.1.4 on 2025-04-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
