# Generated by Django 5.1.4 on 2025-04-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
    ]
