# Generated by Django 5.1.4 on 2025-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_date_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('NOT YET DELIVERED', 'NOT YET DELIVERED'), ('DELIVERED', 'DELIVERED')], default='NOT YET DELIVERED', max_length=17),
        ),
    ]
