name: tiz-ecommerce
services:
- name: web
  source_dir: /
  github:
    repo: deneasato/TIZ-Ecommerce
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm ecommerce.wsgi
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: DEBUG
    value: "False"
  - key: DJANGO_SETTINGS_MODULE
    value: ecommerce.settings
databases:
- name: db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
