# Generated by Django 5.1.4 on 2025-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='email_activated',
            field=models.BooleanField(default=False),
        ),
    ]
