# Generated by Django 5.1.4 on 2025-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_storeuser_email_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
