# Generated by Django 5.1.4 on 2025-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_storeuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='email_activated',
            field=models.BooleanField(default=True),
        ),
    ]
