# Generated by Django 5.1.4 on 2025-03-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_storeuser_email_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='email_activated',
        ),
    ]
