# Generated by Django 5.1.4 on 2025-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_storeuser_email_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
